automated dev commit

diff --git a/setup2 b/setup2
--- a/setup2
+++ b/setup2
@@ -33,3 +33,26 @@ execute_scripts() {
 }
 
 execute_scripts "${root_scripts[@]}"
+
+answer3=$(gum choose "Yes" "No" --height 10 --header "Set up development environment?")
+if [[ "${answer3}" == "Yes" ]]; then
+    if [[ -x "$HOME/dev/dev-env" ]]; then
+        export DEV_ENV="$HOME/dev"
+        "$HOME/dev/dev-env"
+    else
+        echo "Error: $HOME/dev/dev-env is not executable or does not exist."
+        exit 1
+    fi
+else
+    echo "Exiting."
+    exit 0
+fi
+
+
+answer4=$(gum choose "Yes" "No" --height 10 --header "Reboot?")
+if [[ "${answer4}" == "Yes" ]]; then
+    reboot
+else
+    echo "Exiting."
+    exit 0
+fi
