automated dev commit

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -61,15 +61,24 @@ else
     exit 0
 fi
 
-if $RUNNING_GNOME; then
-  gsettings set org.gnome.desktop.screensaver lock-enabled true
-  gsettings set org.gnome.desktop.session idle-delay 300
-fi
 
-answer4=$(gum choose "Yes" "No" --height 10 --header "Reboot?\n\nRun setup2 after boot")
-if [[ "${answer4}" == "Yes" ]]; then
-    reboot
+answer3=$(gum choose "Yes" "No" --height 10 --header "Set up development environment?")
+if [[ "${answer3}" == "Yes" ]]; then
+    if [[ -x "$HOME/dev/dev-env" ]]; then
+        export DEV_ENV="$HOME/dev"
+        "$HOME/dev/dev-env"
+    else
+        echo "Error: $HOME/dev/dev-env is not executable or does not exist."
+        exit 1
+    fi
 else
     echo "Exiting."
     exit 0
 fi
+
+if $RUNNING_GNOME; then
+    gsettings set org.gnome.desktop.screensaver lock-enabled true
+    gsettings set org.gnome.desktop.session idle-delay 300
+fi
+
+echo "Restart terminal and run setup2"
