runs

diff --git a/env/tmux-sessionizer b/env/tmux-sessionizer
--- a/env/tmux-sessionizer
+++ b/env/tmux-sessionizer
@@ -9,10 +9,7 @@
 #
 ################################################################################
 
-
-#Find Directory
-
-
+# Usage information
 usage="\
 --------------------------------------------------------------------------------
 TMUX Sessionizer
@@ -59,7 +56,6 @@ magenta='\033[0;35m'
 cyan='\033[0;36m'
 clear='\033[0m'
 
-
 recursive='false' # A list of directories
 name=''
 help='false'
@@ -85,7 +81,6 @@ sub_dirs=""
 session_dirs=""
 selected_dir=""
 
-
 if [[ "$help" = true ]]; then
   echo "$usage"
   exit 2
@@ -100,35 +95,36 @@ log() {
 
 # Verbose is basically just debug
 verbose() {
-
   if [ "$verbose" = true ]; then
-
     echo -e >&2 "${yellow}$1${clear}"
-
   fi
 }
 
 switch_to() {
-    if [[ -z $TMUX ]]; then
-        tmux attach-session -t $1
-    else
-        tmux switch-client -t $1
-    fi
+  if [[ -z "$1" ]]; then
+    log "${red}Error${clear}: No session name provided to switch to"
+    exit 1
+  fi
+  if [[ -z $TMUX ]]; then
+    tmux attach-session -t "$1"
+  else
+    tmux switch-client -t "$1"
+  fi
 }
 
 has_session() {
-    tmux list-sessions | grep -q "^$1:"
+  tmux list-sessions | grep -q "^$1:"
 }
 
 hydrate() {
-    if [ -f $2/.tmux-sessionizer ]; then
-        tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
-    elif [ -f $HOME/.tmux-sessionizer ]; then
-        tmux send-keys -t $1 "source $HOME/.tmux-sessionizer" c-M
-    fi
+  if [ -f "$2/.tmux-sessionizer" ]; then
+    tmux send-keys -t "$1" "source $2/.tmux-sessionizer" C-m
+  elif [ -f "$HOME/.tmux-sessionizer" ]; then
+    tmux send-keys -t "$1" "source $HOME/.tmux-sessionizer" C-m
+  fi
 }
 
-open_session(){
+open_session() {
   local name=$1
   local dir=$2
   local tmux_running=$(pgrep tmux)
@@ -138,131 +134,126 @@ open_session(){
   verbose "Directory: $dir"
 
   if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-      tmux new-session -s $name -c $dir -e "TMUX_SESSIONIZER_PROJECT_DIR=\"$dir\"" -e "TMUX_SESSIONIZER_PROJECT_NAME=\"$name\""
-      hydrate $name $dir
-      exit 0
+    tmux new-session -s "$name" -c "$dir" -e "TMUX_SESSIONIZER_PROJECT_DIR=\"$dir\"" -e "TMUX_SESSIONIZER_PROJECT_NAME=\"$name\""
+    hydrate "$name" "$dir"
+    exit 0
   fi
 
-  if ! has_session $name; then
-      tmux new-session -ds $name -c $dir -e "TMUX_SESSIONIZER_PROJECT_DIR=\"$dir\"" -e "TMUX_SESSIONIZER_PROJECT_NAME=\"$name\""
-      hydrate $name $dir
+  if ! has_session "$name"; then
+    tmux new-session -ds "$name" -c "$dir" -e "TMUX_SESSIONIZER_PROJECT_DIR=\"$dir\"" -e "TMUX_SESSIONIZER_PROJECT_NAME=\"$name\""
+    hydrate "$name" "$dir"
   fi
 
-  switch_to $name
+  switch_to "$name"
 }
 
-test_directories(){
-  for i in $*; do
-
+test_directories() {
+  for i in "$@"; do
     if [[ ! -d "$i" ]]; then
       log "${red}Error${clear}: Not a valid directory $i"
       return 1
     fi
-
   done
   return 0
 }
 
-get_sub_directories(){
-
-  for i in $*; do
-    sub_dirs="$sub_dirs "$( find "$i" -mindepth 1 -maxdepth 1 -type d)
+get_sub_directories() {
+  sub_dirs=""
+  for i in "$@"; do
+    sub_dirs="$sub_dirs "$(find "$i" -mindepth 1 -maxdepth 1 -type d)
   done
 
   if [[ "$sub_dirs" = "" ]]; then
     return 1
   fi
 
+  verbose "Subdirectories found: $sub_dirs"
   return 0
 }
 
-
 # Adds Prefix of [i/o] to directories
-tmux_session_status(){
+tmux_session_status() {
   local sessions=""
 
   if [[ -n "$TMUX" ]]; then
     sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)
   fi 
 
-  for d in $*; do
-    local dir_name="$( basename "$d" | tr . _ )"
+  for d in "$@"; do
+    local dir_name="$(basename "$d" | tr . _)"
     local match=false
 
     for s in $sessions; do
       if [[ "$dir_name" == "$s" ]]; then
-        printf "i,$d\n"
+        printf "i,%s\n" "$d"
         match=true
         break
       fi
     done
 
     if [ "$match" = false ]; then
-       printf "o,$d\n"
+      printf "o,%s\n" "$d"
     fi
   done
 }
 
-
-select_directory(){
+select_directory() {
   local fzf_default=( '--header-lines=1' 
                       '--color=dark'  
                       '--ansi' 
-                      '--delimiter' '/'
-                      '--nth' '1,-1'
-                      '--with-nth' '1,-1' )
+                      '--delimiter' ','  
+                      '--nth' '2..'     
+                      '--with-nth' '1..' )
   local fzf_preview=()
-  local fzf_header='status,/directory' 
-  local start_icon=$( printf "${green}${clear}" )
-  local stop_icon=$( printf "${yellow}${clear}" ) 
+  local fzf_header='status,directory' 
+  local start_icon=$(printf "${green}●${clear}")
+  local stop_icon=$(printf "${yellow}○${clear}") 
 
   if "$preview"; then
-    # TMUX changes all periods(.) to underscores(_)
     preview_script="\
-        session_name=\"\$( echo {-1} | sed 's/\\./_/g' )\"
+        session_name=\"\$( echo {2..} | sed 's/\\./_/g' | xargs basename )\"
         tmux capture-pane -ept \$session_name 2>/dev/null
       "
     fzf_preview=( '--preview' "$preview_script"
                   '--preview-window' 'nohidden' 
-                  '--preview-label' 'Session'  )
+                  '--preview-label' 'Session' )
   fi
 
   verbose "Number of directories passed: $#"
   
   # Read from stdin instead of arguments
   selected_dir=$( { echo "$fzf_header"; cat; } | \
+                   sed "s/^i/${start_icon}/;s/^o/${stop_icon}/" | \
                    column -s, -t | \
-                   sed s/^i/"${start_icon}"/\;s/^o/"${stop_icon}"/ |  \
                    fzf "${fzf_default[@]}" "${fzf_preview[@]}" | \
-                   awk '{ print $2 }' )
+                   cut -d',' -f2- | sed 's/[^[:alnum:]/._-]//g' )
 
-  if [[ "$selected_dir" = ""  ]];then
-    log "${red}Error${clear}: Fzf failed to retrieve directory from selection"
-    return 1
+  if [[ -z "$selected_dir" ]]; then
+    log "${red}Error${clear}: No directory selected"
+    exit 1
   fi
 
   verbose "Selected Dir: $selected_dir"
   return 0
 }
 
-get_name(){
-
+get_name() {
   if [[ "$name" = '' ]]; then 
-
-    if ! name=$( basename "$1" | tr . _ ); then
-      log "${red}Error${clear}: Getting basename failed, $selected_dir"
+    verbose "Input to basename: $1"
+    if ! name=$(basename "$1" | tr . _); then
+      log "${red}Error${clear}: Getting basename failed for '$1'"
       return 1
     fi 
-
+    if [[ -z "$name" ]]; then
+      log "${red}Error${clear}: Basename is empty for '$1'"
+      return 1
+    fi
     verbose "Basename: $name"
-
   fi
-
   return 0
 }
 
 #---------------------------------Execution-------------------------------------
-
 
 if [[ $dirs = "" ]]; then
   log "$usage" 
@@ -271,45 +262,39 @@ fi
 
 verbose "Directory Count: $#"
 
-if [[ $recursive = false && $# = 1  ]]; then
-
-  if ! test_directories $dirs ; then
-   exit 1
+if [[ $recursive = false && $# = 1 ]]; then
+  if ! test_directories $dirs; then
+    exit 1
   fi
   
   selected_dir="$dirs"
 
-  if ! get_name $selected_dir; then
+  if ! get_name "$selected_dir"; then
     exit 1
   fi 
   
-  open_session $name $selected_dir
-
+  open_session "$name" "$selected_dir"
   exit 0
 fi
 
-
 if [[ $recursive = false ]]; then
-
-  if ! test_directories $dirs ; then
-   exit 1
+  if ! test_directories $dirs; then
+    exit 1
   fi
 
   tmux_session_status $dirs | sort | select_directory
 
-  if ! get_name $selected_dir; then
+  if ! get_name "$selected_dir"; then
     exit 1
   fi 
 
-  open_session $name $selected_dir
-
+  open_session "$name" "$selected_dir"
   exit 0
 fi
 
 if [[ $recursive = true ]]; then
-
-  if ! test_directories $dirs ; then
-   exit 1
+  if ! test_directories $dirs; then
+    exit 1
   fi
 
   if ! get_sub_directories $dirs; then
@@ -321,12 +306,11 @@ if [[ $recursive = true ]]; then
   
   tmux_session_status $sub_dirs | sort | select_directory
 
-  if ! get_name $selected_dir; then
+  if ! get_name "$selected_dir"; then
     exit 1
   fi 
 
-  open_session $name $selected_dir
-
+  open_session "$name" "$selected_dir"
   exit 0
 fi
 
